import React, { useState } from 'react'

export default function A4Sheet({ title, notes, onChat }) {
  const [question, setQuestion] = useState('')

  const handleSubmit = (e) => {
    e.preventDefault()
    if (!question.trim()) return
    onChat(question)
    setQuestion('')
  }

  return (
    <div className="flex-1 flex flex-col items-center bg-gray-800/20 p-8 overflow-y-auto">
      {/* A4 Card */}
      <div className="w-[210mm] min-h-[297mm] bg-white text-gray-900 shadow-2xl rounded-sm p-[25mm] flex flex-col mb-20 relative">
        <h2 className="text-2xl font-bold border-b-2 border-primary-600 pb-4 mb-8">
          {title || "Study Notes"}
        </h2>
        
        <div className="flex-1 text-lg leading-relaxed space-y-4">
          {notes ? (
            <div 
              className="prose prose-slate max-w-none"
              dangerouslySetInnerHTML={{ __html: notes.replace(/\n/g, '<br/>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }}
            />
          ) : (
            <div className="flex flex-col items-center justify-center h-96 text-gray-300">
              <span className="text-5xl mb-4">📄</span>
              <p>Upload a PDF to see generated notes here.</p>
            </div>
          )}
        </div>

        {/* Watermark style footer */}
        <div className="absolute bottom-10 left-1/2 -translate-x-1/2 opacity-20 text-xs font-bold uppercase tracking-widest text-primary-600">
          Generated by StudyBuddy
        </div>
      </div>

      {/* Chat Bar Overlay */}
      <div className="fixed bottom-32 left-[35%] -translate-x-1/2 w-[600px] z-40 px-4">
        <form onSubmit={handleSubmit} className="flex bg-white shadow-2xl rounded-2xl overflow-hidden border-2 border-primary-100">
          <input 
            type="text"
            className="flex-1 px-6 py-4 text-gray-800 focus:outline-none text-lg"
            placeholder="Ask Sensei anything about this content..."
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
          />
          <button type="submit" className="bg-primary-600 text-white px-8 font-bold hover:bg-primary-500 transition-colors">
            Ask Sensei
          </button>
        </form>
      </div>
    </div>
  )
}
